_target_: lewm.FlowJEPA

n_euler_steps: 10

time_proj_mlp:
  _target_: lewm.MLP
  input_dim: 256  # FREQ_DIM
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}

encoder:
  _target_: stable_pretraining.backbone.utils.vit_hf
  size: tiny
  patch_size: 14
  image_size: ${img_size}
  pretrained: false
  use_mask_token: false

predictor:
  _target_: lewm.ARPredictor
  num_frames: ${eval:'${history_size} * 2'}  # 2*ctx_len covers both training (6 tokens) and inference (4 tokens)
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: lewm.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: lewm.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: lewm.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
